In [1]:
import torch
torch.set_printoptions(sci_mode=False)

In [2]:
from math import sqrt

def channel_matrix(m, ch_rows, ch_cols):
    rows, cols = m.shape
    rn, cn = rows // ch_rows, cols // ch_cols
    r = torch.zeros(ch_rows, ch_cols, rn, cn)
    print(r.shape)
    for chr_r in range(ch_rows):
        for chr_c in range(ch_cols):
            for i in range(rn):
                for j in range(cn):
                    r[chr_r, chr_c, i, j] = m[i * rn +chr_r, j * cn+ chr_c]
    print(rn, cn)
    return r.reshape(ch_rows * ch_cols, rn, cn)
m = torch.arange(16).reshape(4, 4)
print(m)
channel_matrix(m, 2, 2)#.shape

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
torch.Size([2, 2, 2, 2])
2 2


tensor([[[ 0.,  2.],
         [ 8., 10.]],

        [[ 1.,  3.],
         [ 9., 11.]],

        [[ 4.,  6.],
         [12., 14.]],

        [[ 5.,  7.],
         [13., 15.]]])

In [3]:
channel_matrix(m, 1, 1)

torch.Size([1, 1, 4, 4])


IndexError: index 4 is out of bounds for dimension 1 with size 4

In [36]:
def channel_matrix(m, ch_rows, ch_cols):
    rows, cols = m.shape
    rn, cn = rows // ch_rows, cols // ch_cols
    r = torch.zeros(ch_rows, ch_cols, rn, cn)
    assert r.numel() == m.numel()    
    for chr_r in range(ch_rows):
        for chr_c in range(ch_cols):
            for i in range(rn):
                for j in range(cn):           
                    print(i, j, chr_r, chr_c)
                    print(i * ch_rows +chr_r, j * ch_cols+ chr_c)
                    r[chr_r, chr_c, i, j] = m[i * ch_rows +chr_r, j * ch_cols+ chr_c]    
    return r

m = torch.arange(64).reshape(8, 8)
channel_matrix(m, 2, 2)#.shape

4 4 torch.Size([2, 2, 4, 4])
0 0 0 0
0 0
0 1 0 0
0 2
0 2 0 0
0 4
0 3 0 0
0 6
1 0 0 0
2 0
1 1 0 0
2 2
1 2 0 0
2 4
1 3 0 0
2 6
2 0 0 0
4 0
2 1 0 0
4 2
2 2 0 0
4 4
2 3 0 0
4 6
3 0 0 0
6 0
3 1 0 0
6 2
3 2 0 0
6 4
3 3 0 0
6 6
0 0 0 1
0 1
0 1 0 1
0 3
0 2 0 1
0 5
0 3 0 1
0 7
1 0 0 1
2 1
1 1 0 1
2 3
1 2 0 1
2 5
1 3 0 1
2 7
2 0 0 1
4 1
2 1 0 1
4 3
2 2 0 1
4 5
2 3 0 1
4 7
3 0 0 1
6 1
3 1 0 1
6 3
3 2 0 1
6 5
3 3 0 1
6 7
0 0 1 0
1 0
0 1 1 0
1 2
0 2 1 0
1 4
0 3 1 0
1 6
1 0 1 0
3 0
1 1 1 0
3 2
1 2 1 0
3 4
1 3 1 0
3 6
2 0 1 0
5 0
2 1 1 0
5 2
2 2 1 0
5 4
2 3 1 0
5 6
3 0 1 0
7 0
3 1 1 0
7 2
3 2 1 0
7 4
3 3 1 0
7 6
0 0 1 1
1 1
0 1 1 1
1 3
0 2 1 1
1 5
0 3 1 1
1 7
1 0 1 1
3 1
1 1 1 1
3 3
1 2 1 1
3 5
1 3 1 1
3 7
2 0 1 1
5 1
2 1 1 1
5 3
2 2 1 1
5 5
2 3 1 1
5 7
3 0 1 1
7 1
3 1 1 1
7 3
3 2 1 1
7 5
3 3 1 1
7 7
4 4


tensor([[[[ 0.,  2.,  4.,  6.],
          [16., 18., 20., 22.],
          [32., 34., 36., 38.],
          [48., 50., 52., 54.]],

         [[ 1.,  3.,  5.,  7.],
          [17., 19., 21., 23.],
          [33., 35., 37., 39.],
          [49., 51., 53., 55.]]],


        [[[ 8., 10., 12., 14.],
          [24., 26., 28., 30.],
          [40., 42., 44., 46.],
          [56., 58., 60., 62.]],

         [[ 9., 11., 13., 15.],
          [25., 27., 29., 31.],
          [41., 43., 45., 47.],
          [57., 59., 61., 63.]]]])

In [23]:
m

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])

In [12]:
def channel_matrix(m, ch_rows, ch_cols):
    rows, cols = m.shape
    rn, cn = rows // ch_rows, cols // ch_cols
    r = torch.zeros(ch_rows, ch_cols, rn, cn)
    assert r.numel() == m.numel()    
    for chr_r in range(ch_rows):
        for chr_c in range(ch_cols):
            for i in range(rn):
                for j in range(cn):                               
                    r[chr_r, chr_c, i, j] = m[i * ch_rows + chr_r, j * ch_cols+ chr_c]
    return r

m = torch.arange(16).reshape(4, 4)
channel_matrix(m, 2, 2)#.shape

tensor([[[[ 0.,  2.],
          [ 8., 10.]],

         [[ 1.,  3.],
          [ 9., 11.]]],


        [[[ 4.,  6.],
          [12., 14.]],

         [[ 5.,  7.],
          [13., 15.]]]])

In [11]:
m = torch.arange(128**2).reshape(128, 128)
m.shape

torch.Size([128, 128])

In [46]:
r = channel_matrix(m, 2, 2)
r.shape

torch.Size([2, 2, 64, 64])

In [ ]:
r = channel_matrix(m, 2, 2)
r.shape

In [9]:

m = torch.arange(16).reshape(4, 4)
channel_matrix(m, 1, 1)#.shape

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])