In [2]:
import torch
import pytorch3d

from pytorch3d.structures import Meshes

In [6]:
verts_list = [torch.tensor([]), torch.tensor([])]
faces_list = [torch.tensor([]), torch.tensor([])]
mesh_batch = Meshes(verts=verts_list, faces=faces_list)

In [7]:
mesh_batch.verts_packed()

tensor([], size=(0, 3))

In [9]:
mesh_to_vert_idx = mesh_batch.mesh_to_verts_packed_first_idx()
mesh_to_vert_idx

tensor([], dtype=torch.int64)

In [10]:
edges = mesh_batch.edges_packed()

In [11]:
import torch
from pytorch3d.io import load_obj



In [12]:
verts, faces, aux  = load_obj('./data/teapot.obj')
verts, faces, aux

(tensor([[-0.4985,  0.7125, -0.0399],
         [-0.5017,  0.6992, -0.0638],
         [-0.5013,  0.7178,  0.0000],
         ...,
         [ 0.6177,  0.2359, -0.0859],
         [ 0.6194,  0.2831, -0.1372],
         [ 0.6194,  0.2831,  0.1372]]),
 Faces(verts_idx=tensor([[  33, 1242,  592],
         [  51,   26,   39],
         [  51,   39,   64],
         ...,
         [ 190,  184,  168],
         [ 189,  198,  177],
         [ 217,  198,  189]]), normals_idx=tensor([[   0,    1,    2],
         [   3,    4,    5],
         [   3,    5,    6],
         ...,
         [ 235, 1237, 1236],
         [1288,  207, 1286],
         [ 213,  207, 1288]]), textures_idx=tensor([[-1, -1, -1],
         [-1, -1, -1],
         [-1, -1, -1],
         ...,
         [-1, -1, -1],
         [-1, -1, -1],
         [-1, -1, -1]]), materials_idx=tensor([-1, -1, -1,  ..., -1, -1, -1])),
 Properties(normals=tensor([[-0.9019,  0.4154,  0.1182],
         [-0.9056,  0.4071,  0.1187],
         [-0.8770,  0.4187,  0.23

In [13]:
aux.normals

tensor([[-0.9019,  0.4154,  0.1182],
        [-0.9056,  0.4071,  0.1187],
        [-0.8770,  0.4187,  0.2353],
        ...,
        [ 0.0558, -0.0176,  0.9983],
        [ 0.2942, -0.8554,  0.4263],
        [ 0.2013, -0.5409,  0.8166]])

In [14]:
aux.texture_atlas

In [15]:
aux.texture_images

In [16]:
aux.verts_uvs

In [17]:
aux.material_colors

In [18]:
batched_mesh = pytorch3d.io.load_objs_as_meshes(['./data/teapot.obj'])

In [19]:
batched_mesh

In [20]:
isinstance(batched_mesh, Meshes)

True

In [21]:
len(batched_mesh)

1

In [22]:
from pytorch3d.transforms import Transform3d, Rotate, Translate

In [23]:
# example 1
T = Translate(torch.FloatTensor([[1.0, 2.0, 3.0]]))
R = Rotate(torch.FloatTensor([[0.0, 1.0, 0.0], 
                              [0.0, 0.0, 1.0],
                              [1.0, 0.0, 0.0],
                             ]))
RT = Transform3d().compose(R, T)

In [24]:
T = Transform3d().scale(2, 1, 3).translate(1, 2, 3)

In [25]:
from pytorch3d.ops import knn_points

N, P1, P2, D, K = 32, 128, 256, 3, 1

pts1 = torch.randn(N, P1, D)
pts2 = torch.rand(N, P2, D)

In [27]:
dists, idx, knn = knn_points(pts1, pts2, K=K)
dists, idx, knn

(tensor([[[1.4290e+00],
          [8.4930e-03],
          [2.2461e-01],
          ...,
          [1.4522e-01],
          [4.4890e+00],
          [1.4988e+00]],
 
         [[3.0449e-01],
          [9.2938e-01],
          [1.0291e+01],
          ...,
          [6.4463e-02],
          [1.7473e+00],
          [2.9075e+00]],
 
         [[9.9870e-01],
          [1.5493e+00],
          [4.5603e-01],
          ...,
          [1.3994e-01],
          [8.1903e+00],
          [6.6683e-01]],
 
         ...,
 
         [[1.8013e+00],
          [7.1657e-01],
          [2.8127e+00],
          ...,
          [4.2455e+00],
          [2.5243e-01],
          [4.6955e+00]],
 
         [[2.8929e-01],
          [1.8864e+00],
          [9.6867e-01],
          ...,
          [4.2351e-01],
          [7.0330e-01],
          [9.7388e-01]],
 
         [[4.6270e+00],
          [7.8505e-01],
          [2.8509e-01],
          ...,
          [2.3710e+00],
          [7.8456e-02],
          [8.3677e+00]]]),
 tensor([[[1

In [28]:
from pytorch3d.ops import GraphConv

conv = GraphConv()

TypeError: __init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'

In [29]:
from pytorch3d.utils import ico_sphere
from pytorch3d.ops import sample_points_from_meshes
from pytorch3d.loss import chamfer_distance

In [30]:
sphere_mesh1 = ico_sphere(level=3)
sphere_mesh2 = ico_sphere(level=1)

sample_sphere = sample_points_from_meshes(sphere_mesh1, 5000)
sample_test = sample_points_from_meshes(sphere_mesh2, 5000)

loss_chamfer, _ = chamfer_distance(sample_sphere, sample_test)
loss_chamfer

tensor(0.0052)

In [32]:
from pytorch3d.renderer import (
    OpenGLPerspectiveCameras, look_at_view_transform,
    RasterizationSettings, BlendParams,
    MeshRenderer, MeshRasterizer, HardPhongShader,
)

R, T = look_at_view_transform(2.7, 10, 20)
cameras = OpenGLPerspectiveCameras(device=torch.device("cuda"), R=R, T=T)

raster_settings = RasterizationSettings(
    image_size=512,
    blur_radius=0.0,
    faces_per_pixel=1, # Sets the value of K
)


In [33]:
evice=torch.device("cuda")
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(cameras=cameras, 
        raster_settings=raster_settings),
    shader=HardPhongShader(device=device, cameras=cameras)
)

image = renderer(mesh)

# compute  a loss give a ground truth image
loss = (gt_img - img).sum()

loss.backward()

NameError: name 'device' is not defined