In [21]:
import torch
from  models.guidingNet import GuidingNet
from models.generator import Generator
from models.discriminator import Discriminator

In [2]:
GN = GuidingNet()
GN

GuidingNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (8): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU()
    (11): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (12): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (13): ReLU()
    (14): MaxPool2d(kernel_size=2, stride=2, padding=0, dilatio

In [4]:
G = Generator()
G

Init Generator
GENERATOR NF :  64
Init ContentEncoder
Init Decoder


Generator(
  (cnt_encoder): ContentEncoder(
    (model): Sequential(
      (0): Conv2dBlock(
        (pad): ReflectionPad2d((3, 3, 3, 3))
        (norm): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (activation): ReLU(inplace=True)
        (conv): Conv2d(3, 64, kernel_size=(7, 7), stride=(1, 1))
      )
      (1): Conv2dBlock(
        (pad): ReflectionPad2d((1, 1, 1, 1))
        (norm): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (activation): ReLU(inplace=True)
        (conv): Conv2d(64, 128, kernel_size=(4, 4), stride=(2, 2))
      )
      (2): Conv2dBlock(
        (pad): ReflectionPad2d((1, 1, 1, 1))
        (norm): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
        (activation): ReLU(inplace=True)
        (conv): Conv2d(128, 256, kernel_size=(4, 4), stride=(2, 2))
      )
      (3): Conv2dBlock(
        (pad): ReflectionPad2d((1, 1, 1, 1))
   

In [5]:
G.cnt_encoder

ContentEncoder(
  (model): Sequential(
    (0): Conv2dBlock(
      (pad): ReflectionPad2d((3, 3, 3, 3))
      (norm): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      (activation): ReLU(inplace=True)
      (conv): Conv2d(3, 64, kernel_size=(7, 7), stride=(1, 1))
    )
    (1): Conv2dBlock(
      (pad): ReflectionPad2d((1, 1, 1, 1))
      (norm): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      (activation): ReLU(inplace=True)
      (conv): Conv2d(64, 128, kernel_size=(4, 4), stride=(2, 2))
    )
    (2): Conv2dBlock(
      (pad): ReflectionPad2d((1, 1, 1, 1))
      (norm): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      (activation): ReLU(inplace=True)
      (conv): Conv2d(128, 256, kernel_size=(4, 4), stride=(2, 2))
    )
    (3): Conv2dBlock(
      (pad): ReflectionPad2d((1, 1, 1, 1))
      (norm): InstanceNorm2d(512, eps=1e-05, momentum=0.1, affine=False, 

In [6]:
G.decoder

Decoder(
  (model): Sequential(
    (0): ResBlocks(
      (model): Sequential(
        (0): ResBlock(
          (model): Sequential(
            (0): Conv2dBlock(
              (pad): ReflectionPad2d((1, 1, 1, 1))
              (norm): AdaIN2d(num_features=512)
              (activation): ReLU(inplace=True)
              (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1))
            )
            (1): Conv2dBlock(
              (pad): ReflectionPad2d((1, 1, 1, 1))
              (norm): AdaIN2d(num_features=512)
              (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1))
            )
          )
        )
        (1): ResBlock(
          (model): Sequential(
            (0): Conv2dBlock(
              (pad): ReflectionPad2d((1, 1, 1, 1))
              (norm): AdaIN2d(num_features=512)
              (activation): ReLU(inplace=True)
              (conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1))
            )
            (1): Conv2dBlock(
              (p

In [8]:
G.cnt_encoder(torch.rand(1, 3, 128, 128)).shape

torch.Size([1, 512, 16, 16])

In [13]:
res = GN(torch.rand(1, 3, 128, 128))
res['cont'].shape, res['disc'].shape

(torch.Size([1, 128]), torch.Size([1, 10]))

In [11]:
G.mlp

MLP(
  (model): Sequential(
    (0): LinearBlock(
      (fc): Linear(in_features=64, out_features=256, bias=True)
      (activation): ReLU(inplace=True)
    )
    (1): LinearBlock(
      (fc): Linear(in_features=256, out_features=256, bias=True)
      (activation): ReLU(inplace=True)
    )
    (2): LinearBlock(
      (fc): Linear(in_features=256, out_features=4992, bias=True)
    )
  )
)

In [12]:
G.mlp(res['cont'])

RuntimeError: size mismatch, m1: [1 x 128], m2: [64 x 256] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41

In [14]:
C = GuidingNet(64)
G = Generator(64, 128, 4)
x_in = torch.randn(4, 3, 64, 64)
cont = G.cnt_encoder(x_in)
sty = C.moco(x_in)
x_out = G.decode(cont, sty)

Init Generator
GENERATOR NF :  64
Init ContentEncoder
Init Decoder


In [16]:
sty.shape

torch.Size([4, 128])

In [18]:
G.mlp(sty).shape

torch.Size([4, 4480])

In [19]:
G.mlp(res['cont'])

tensor([[-0.1442,  0.1311,  0.1664,  ..., -0.0737,  0.0959, -0.4792]],
       grad_fn=<AddmmBackward>)

In [22]:
D = Discriminator(64, 10)
x_in = torch.randn(4, 3, 64, 64)
y_in = torch.randint(0, 10, size=(4, ))
out, feat = D(x_in, y_in)
print(out.shape, feat.shape)

torch.Size([4]) torch.Size([4, 10, 1, 1])


In [24]:
D

Discriminator(
  (main): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ActFirstResBlk(
      (norm1): FRN()
      (norm2): FRN()
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (2): ActFirstResBlk(
      (norm1): FRN()
      (norm2): FRN()
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv1x1): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
    )
    (3): ActFirstResBlk(
      (norm1): FRN()
      (norm2): FRN()
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    )
    (4): ActFirstResBlk(
      (norm1): FRN()
      (norm2): FRN()
      (conv1): Conv2d(128, 128, 

In [31]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import torch.nn.init as init

import math

try:
    from models.blocks import FRN, ActFirstResBlk
except:
    from blocks import FRN, ActFirstResBlk


class Discriminator(nn.Module):
    """Discriminator: (image x, domain y) -> (logit out)."""
    def __init__(self, image_size=256, num_domains=2, max_conv_dim=1024):
        super(Discriminator, self).__init__()
        dim_in = 64 if image_size < 256 else 32
        blocks = []
        blocks += [nn.Conv2d(3, dim_in, 3, 1, 1)]

        repeat_num = int(np.log2(image_size)) - 2
        for _ in range(repeat_num):
            dim_out = min(dim_in*2, max_conv_dim)
            blocks += [ActFirstResBlk(dim_in, dim_in, downsample=False)]
            blocks += [ActFirstResBlk(dim_in, dim_out, downsample=True)]
            dim_in = dim_out

        blocks += [nn.LeakyReLU(0.2)]
        blocks += [nn.Conv2d(dim_out, dim_out, 4, 1, 0)]
        blocks += [nn.LeakyReLU(0.2)]
        blocks += [nn.Conv2d(dim_out, num_domains, 1, 1, 0)]
        self.main = nn.Sequential(*blocks)

        self.apply(weights_init('kaiming'))

    def forward(self, x, y):
        """
        Inputs:
            - x: images of shape (batch, 3, image_size, image_size).
            - y: domain indices of shape (batch).
        Output:
            - out: logits of shape (batch).
        """
        out = self.main(x)
        feat = out
        out = out.view(out.size(0), -1)                          # (batch, num_domains)
        idx = torch.LongTensor(range(y.size(0))).to(y.device)
        out = out[idx, y]                                         # (batch)
        return out, feat

    def _initialize_weights(self, mode='fan_in'):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode=mode, nonlinearity='relu')
                if m.bias is not None:
                    m.bias.data.zero_()


def weights_init(init_type='gaussian'):
    def init_fun(m):
        classname = m.__class__.__name__
        if (classname.find('Conv') == 0 or classname.find(
                'Linear') == 0) and hasattr(m, 'weight'):
            if init_type == 'gaussian':
                init.normal_(m.weight.data, 0.0, 0.02)
            elif init_type == 'xavier':
                init.xavier_normal_(m.weight.data, gain=math.sqrt(2))
            elif init_type == 'kaiming':
                init.kaiming_normal_(m.weight.data, a=0, mode='fan_in')
            elif init_type == 'orthogonal':
                init.orthogonal_(m.weight.data, gain=math.sqrt(2))
            elif init_type == 'default':
                pass
            else:
                assert 0, "Unsupported initialization: {}".format(init_type)
            if hasattr(m, 'bias') and m.bias is not None:
                init.constant_(m.bias.data, 0.0)
    return init_fun

D = Discriminator(64, 10)
x_in = torch.randn(4, 3, 64, 64)
y_in = torch.randint(0, 10, size=(4, ))
out, feat = D(x_in, y_in)
print(out.shape, feat.shape)

torch.Size([4]) torch.Size([4, 10, 1, 1])


In [28]:
feat = out
out = feat.view(out.size(0), -1)                          # (batch, num_domains)
print(out)
y = y_in
idx = torch.LongTensor(range(y.size(0))).to(y.device)
idx
# out = out[idx, y]   

tensor([[-0.7367],
        [-0.7327],
        [ 0.8354],
        [-0.6063]], grad_fn=<ViewBackward>)


tensor([0, 1, 2, 3])

In [33]:
feat.shape

torch.Size([4, 10, 1, 1])

In [34]:
y_in

tensor([0, 5, 7, 2])

In [35]:
feat[idx, y]

tensor([[[ 2.0200]],

        [[ 2.1124]],

        [[-2.0205]],

        [[ 0.1798]]], grad_fn=<IndexBackward>)