In [48]:
import torch
from src.util import make_faces

def vertex_tris(faces):
#     res = []
#     face_max = faces.max()+1
#     for vid in range(face_max):
#         if vid % 1000 == 0:
#             print(vid, face_max)
#         vertex_faces = []
#         for fid, face in enumerate(faces):
#             #if vid in face:
#             if vid == face[0] or vid == face[1] or vid == face[2]:
#                 vertex_faces.append(fid)
#         res.append(vertex_faces)
    res = [[] for _ in range(faces.max()+1)]
    for fid, face in enumerate(faces):
        for vid in face:
            res[vid].append(fid)        
    return res

def vertex_tri_maps(faces):
    vts = vertex_tris(faces)
    r, c = len(vts), max([len(x) for  x in vts])
    vert_tri_indices = torch.zeros(r, c, dtype=torch.long)
    vert_tri_weights = torch.zeros(r, c)    
    for r, tris in enumerate(vts):
        if r % 1000 == 0:
            print(r, len(vts))
        weight = 1. / len(tris)
        for c, tri_id in enumerate(tris):
            vert_tri_indices[r, c] = tri_id
            vert_tri_weights[r, c] = weight
    return vert_tri_indices, vert_tri_weights.unsqueeze(dim=-1)[None]

In [49]:
from src.config import get_parser

opt = get_parser().parse_args(args=[])
opt.raster_patch_size = 512
opt.raster_patch_size
#vert_tri_indices, vert_tri_weights = vertex_tri_maps(faces)

16

In [50]:
faces = make_faces(opt.raster_patch_size, opt.raster_patch_size)
faces.shape

(450, 3)

In [51]:
vts = vertex_tris(faces)
vts

[[0],
 [0, 1, 2],
 [2, 3, 4],
 [4, 5, 6],
 [6, 7, 8],
 [8, 9, 10],
 [10, 11, 12],
 [12, 13, 14],
 [14, 15, 16],
 [16, 17, 18],
 [18, 19, 20],
 [20, 21, 22],
 [22, 23, 24],
 [24, 25, 26],
 [26, 27, 28],
 [28, 29],
 [0, 1, 30],
 [1, 2, 3, 30, 31, 32],
 [3, 4, 5, 32, 33, 34],
 [5, 6, 7, 34, 35, 36],
 [7, 8, 9, 36, 37, 38],
 [9, 10, 11, 38, 39, 40],
 [11, 12, 13, 40, 41, 42],
 [13, 14, 15, 42, 43, 44],
 [15, 16, 17, 44, 45, 46],
 [17, 18, 19, 46, 47, 48],
 [19, 20, 21, 48, 49, 50],
 [21, 22, 23, 50, 51, 52],
 [23, 24, 25, 52, 53, 54],
 [25, 26, 27, 54, 55, 56],
 [27, 28, 29, 56, 57, 58],
 [29, 58, 59],
 [30, 31, 60],
 [31, 32, 33, 60, 61, 62],
 [33, 34, 35, 62, 63, 64],
 [35, 36, 37, 64, 65, 66],
 [37, 38, 39, 66, 67, 68],
 [39, 40, 41, 68, 69, 70],
 [41, 42, 43, 70, 71, 72],
 [43, 44, 45, 72, 73, 74],
 [45, 46, 47, 74, 75, 76],
 [47, 48, 49, 76, 77, 78],
 [49, 50, 51, 78, 79, 80],
 [51, 52, 53, 80, 81, 82],
 [53, 54, 55, 82, 83, 84],
 [55, 56, 57, 84, 85, 86],
 [57, 58, 59, 86, 87, 88],
 

In [11]:

def vertex_tris(faces):
    res = []
    for vid in range(faces.max()+1):
        if vid % 1000 == 0:
            print(vid, faces.max()+1)
        vertex_faces = []
        for fid, face in enumerate(faces):
            if vid in face:
                vertex_faces.append(fid)
        res.append(vertex_faces)
    return res

faces = make_faces(opt.raster_patch_size, opt.raster_patch_size)
%lprun  vert_tri_indices, vert_tri_weights = vertex_tri_maps(faces)

0 256
0 256


In [13]:
%lprun -T lprof0 -f vertex_tri_maps vertex_tri_maps(faces)

0 256
0 256

*** Profile printout saved to text file 'lprof0'. 


In [14]:
print(open('lprof0', 'r').read())

Timer unit: 1e-06 s

Total time: 0.339094 s
File: <ipython-input-1-cc5d96e7860d>
Function: vertex_tri_maps at line 14

Line #      Hits         Time  Per Hit   % Time  Line Contents
    14                                           def vertex_tri_maps(faces):
    15         1     319961.0 319961.0     94.4      vts = vertex_tris(faces)
    16         1         44.0     44.0      0.0      r, c = len(vts), max([len(x) for  x in vts])
    17         1         44.0     44.0      0.0      vert_tri_indices = torch.zeros(r, c, dtype=torch.long)
    18         1          6.0      6.0      0.0      vert_tri_weights = torch.zeros(r, c)    
    19       257        116.0      0.5      0.0      for r, tris in enumerate(vts):
    20       256        145.0      0.6      0.0          if r % 1000 == 0:
    21         1        425.0    425.0      0.1              print(r, len(vts))
    22       256        176.0      0.7      0.1          weight = 1. / len(tris)
    23      1606       1029.0      0.6     

In [15]:
%lprun -T lprof1 -f vertex_tris vertex_tris(faces)

0 256

*** Profile printout saved to text file 'lprof1'. 


In [16]:
print(open('lprof1', 'r').read())

Timer unit: 1e-06 s

Total time: 0.386704 s
File: <ipython-input-11-15c0e8056c29>
Function: vertex_tris at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def vertex_tris(faces):
     2         1          1.0      1.0      0.0      res = []
     3       257        126.0      0.5      0.0      for vid in range(faces.max()+1):
     4       256        132.0      0.5      0.0          if vid % 1000 == 0:
     5         1        321.0    321.0      0.1              print(vid, faces.max()+1)
     6       256         83.0      0.3      0.0          vertex_faces = []
     7    115456      60205.0      0.5     15.6          for fid, face in enumerate(faces):
     8    115200     325142.0      2.8     84.1              if vid in face:
     9      1350        560.0      0.4      0.1                  vertex_faces.append(fid)
    10       256        133.0      0.5      0.0          res.append(vertex_faces)
    11         1     

In [22]:
def vertex_tris(faces):
    res = []
    for vid in range(faces.max()+1):
        vertex_faces = []
        for fid, face in enumerate(faces):
            #print(vid, face)
            if vid == face[0] or vid == face[1] or vid == face[2]:                
                vertex_faces.append(fid)
        res.append(vertex_faces)
    return res

%lprun -T lprof2 -f vertex_tris vertex_tris(faces)


*** Profile printout saved to text file 'lprof2'. 


In [23]:
print(open('lprof2', 'r').read())

Timer unit: 1e-06 s

Total time: 0.181714 s
File: <ipython-input-22-1f620d4f92e9>
Function: vertex_tris at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def vertex_tris(faces):
     2         1          1.0      1.0      0.0      res = []
     3       257        118.0      0.5      0.1      for vid in range(faces.max()+1):
     4       256         69.0      0.3      0.0          vertex_faces = []
     5    115456      50104.0      0.4     27.6          for fid, face in enumerate(faces):
     6                                                       #print(vid, face)
     7    115200     130812.0      1.1     72.0              if vid == face[0] or vid == face[1] or vid == face[2]:                
     8      1350        496.0      0.4      0.3                  vertex_faces.append(fid)
     9       256        113.0      0.4      0.1          res.append(vertex_faces)
    10         1          1.0      1.0      0.0    

In [7]:
from collections import OrderedDict

obj = OrderedDict(OrderedDict([
  ('vert_tri_indices', vert_tri_indices),
  ('vert_tri_weights', vert_tri_weights),
  ('faces', torch.tensor(faces[None])),
]))
file = './data/vert_tri_{}.pth'.format(opt.raster_patch_size)
torch.save(obj, file)
file

array([[ 0,  1,  4],
       [ 1,  5,  4],
       [ 1,  2,  5],
       [ 2,  6,  5],
       [ 2,  3,  6],
       [ 3,  7,  6],
       [ 4,  5,  8],
       [ 5,  9,  8],
       [ 5,  6,  9],
       [ 6, 10,  9],
       [ 6,  7, 10],
       [ 7, 11, 10],
       [ 8,  9, 12],
       [ 9, 13, 12],
       [ 9, 10, 13],
       [10, 14, 13],
       [10, 11, 14],
       [11, 15, 14]])

In [8]:
vert_tri_indices.shape, vert_tri_weights.shape

(torch.Size([16384, 6]), torch.Size([1, 16384, 6, 1]))

In [ ]:
import torch 
from collections import OrderedDict

opt = get_parser().parse_args(args=[])


opt.raster_patch_size = raster_patch_size
faces = make_faces(opt.raster_patch_size, opt.raster_patch_size)

loaded =  torch.load(os.path.join(opt.data_dir, 
            'vert_tri_{}.pth'.format(opt.raster_patch_size)))
obj = OrderedDict(OrderedDict([
  ('vert_tri_indices', vert_tri_indices),
  ('vert_tri_weights', vert_tri_weights),
  ('faces', torch.tensor(faces[None])),
])
file = './data/trimap_{}.pth'.format(opt.raster_patch_size)
torch.save(obj, file)

In [9]:
from collections import OrderedDict

obj = OrderedDict(OrderedDict([
  ('vert_tri_indices', vert_tri_indices),
  ('vert_tri_weights', vert_tri_weights),
  ('faces', torch.tensor(faces[None])),
]))
file = './data/vert_tri_{}.pth'.format(opt.raster_patch_size)
torch.save(obj, file)
file

'./data/vert_tri_128.pth'

In [10]:
loaded = torch.load(file)
loaded

OrderedDict([('vert_tri_indices',
              tensor([[    0,     0,     0,     0,     0,     0],
                      [    0,     1,     2,     0,     0,     0],
                      [    2,     3,     4,     0,     0,     0],
                      ...,
                      [32253, 32254, 32255,     0,     0,     0],
                      [32255, 32256, 32257,     0,     0,     0],
                      [32257,     0,     0,     0,     0,     0]])),
             ('vert_tri_weights',
              tensor([[[[1.0000],
                        [0.0000],
                        [0.0000],
                        [0.0000],
                        [0.0000],
                        [0.0000]],
              
                       [[0.3333],
                        [0.3333],
                        [0.3333],
                        [0.0000],
                        [0.0000],
                        [0.0000]],
              
                       [[0.3333],
                        [0.3333]

In [11]:
loaded['vert_tri_indices'].shape, loaded['vert_tri_weights'].shape

(torch.Size([16384, 6]), torch.Size([1, 16384, 6, 1]))

In [ ]:
import numpy as np

def make_faces(w, h):
    mesh_indices = []
    for iw  in range(w-1):
        for ih in range(h-1):
            mesh_indices.append([iw*w+ih, iw*w+ih+1, (iw+1)*w+ih])            
            mesh_indices.append([iw*w+ih+1, (iw+1)*w+ih+1, (iw+1)*w+ih])
    return np.array(mesh_indices)

faces = make_faces(4, 4)
faces

In [44]:

from src.config import get_parser

opt = get_parser().parse_args(args=[])
opt.raster_patch_size = 4
opt.raster_patch_size
#vert_tri_indices, vert_t



faces = make_faces(opt.raster_patch_size , opt.raster_patch_size)
faces.shape

(18, 3)

In [45]:
def vertex_tris(faces):
    res = []
    face_max = faces.max()+1
    for vid in range(face_max):
        if vid % 1000 == 0:
            print(vid, face_max)
        vertex_faces = []
        for fid, face in enumerate(faces):
            #if vid in face:
            if vid == face[0] or vid == face[1] or vid == face[2]:
                vertex_faces.append(fid)
        res.append(vertex_faces)
    return res

vt_tris = vertex_tris(faces)
vt_tris

0 16


[[0],
 [0, 1, 2],
 [2, 3, 4],
 [4, 5],
 [0, 1, 6],
 [1, 2, 3, 6, 7, 8],
 [3, 4, 5, 8, 9, 10],
 [5, 10, 11],
 [6, 7, 12],
 [7, 8, 9, 12, 13, 14],
 [9, 10, 11, 14, 15, 16],
 [11, 16, 17],
 [12, 13],
 [13, 14, 15],
 [15, 16, 17],
 [17]]

In [47]:
res = [[] for _ in range(faces.max()+1)]
for fid, face in enumerate(faces):
    for vid in face:
        res[vid].append(fid)
res

[[0],
 [0, 1, 2],
 [2, 3, 4],
 [4, 5],
 [0, 1, 6],
 [1, 2, 3, 6, 7, 8],
 [3, 4, 5, 8, 9, 10],
 [5, 10, 11],
 [6, 7, 12],
 [7, 8, 9, 12, 13, 14],
 [9, 10, 11, 14, 15, 16],
 [11, 16, 17],
 [12, 13],
 [13, 14, 15],
 [15, 16, 17],
 [17]]